version: '3.8'

services:
  postgres:
    container_name: nest-postgres
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=arenamerlim